---
name: Release

on:
  release:
    types: [published]
  push:
    branches:
      - rdg-testing-release

permissions:
  contents: write

jobs:
  debug-tag:
    name: Set debug tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          ref: 311a3e9f06e2d5f22157c8b27867511a39aeaf5e
      - uses: EndBug/latest-tag@8fcae8848c1e23fd8212258f69a9619bc62cad67
        with:
          ref: testingupdatetag
          description: testing tagging


  # update-stable-tag:
  #   name: Update stable tag
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #   if: ${{ !github.event.release.prerelease }}
  #   steps:
  #     - uses: actions/checkout@7
  #       with: {ref: "${{ github.event.release.tag_name }}"}
  #     - uses: EndBug/latest-tag@8fcae8848c1e23fd8212258f69a9619bc62cad67
  #       with: {ref: stable}

  # update-testing-tag:
  #   name: Update testing tag
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #   steps:
  #     - uses: actions/checkout@7
  #       with: {ref: "${{ github.event.release.tag_name }}"}
  #     - uses: EndBug/latest-tag@8fcae8848c1e23fd8212258f69a9619bc62cad67
  #       with: {ref: testing}
