name: Release

on:
  release:
    types: [published]

jobs:
  update-stable-tag:
    name: Update stable tag
    runs-on: ubuntu-latest
    if: ${{ !github.event.release.prerelease }}
    steps:
      - uses: actions/checkout@v3
        with: {ref: "${{ github.event.release.target_commitish }}"}
      - uses: EndBug/latest-tag@latest
        with: {ref: stable}

  update-testing-tag:
    name: Update testing tag
    runs-on: ubuntu-latest
    if: ${{ github.event.release.prerelease }}
    steps:
      - uses: actions/checkout@v3
        with: {ref: "${{ github.event.release.target_commitish }}"}
      - uses: EndBug/latest-tag@latest
        with: {ref: testing}
